repos:
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.27.0
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.3
    hooks:
      - id: uv-lock
